# -*- coding: utf-8 -*-
"""Sentinel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UKpWagEm87nkASnFrrV5ss_bq2BsOMUw

# Sentinel

## Data collection
"""

import pandas as pd

# Combine datasets
datasets = [
  'https://raw.githubusercontent.com/sentinel-ml/sentinel_ai/refs/heads/main/datasets/data_set_first_qtr.csv',
  'https://raw.githubusercontent.com/sentinel-ml/sentinel_ai/refs/heads/main/datasets/data_set_second_qtr.csv',
  'https://raw.githubusercontent.com/sentinel-ml/sentinel_ai/refs/heads/main/datasets/data_set_third_qtr.csv',
  'https://raw.githubusercontent.com/sentinel-ml/sentinel_ai/refs/heads/main/datasets/data_set_fourth_qtr.csv'
]

df = pd.concat((pd.read_csv(dataset) for dataset in datasets), ignore_index=True)

"""## Data Preprocessing"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split Data
X, y = df.drop(columns='fraud'), df['fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, shuffle=False)

# Scale data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""## Train Model"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

k = 5
distance_metric = 'euclidean'

knn_clf = KNeighborsClassifier(n_neighbors=k, metric=distance_metric)
knn_clf.fit(X_train, y_train)

"""## Prediction"""

prediction = knn_clf.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, prediction)}')

"""## Save Model"""

import pickle

with open('sentinel_0.0.1.pkl', 'wb') as model_file:
  pickle.dump(knn_clf, model_file)

"""# Git"""

!ls